### ISSUE TITLE
Can't assign IP adress with DHCP

### ISSUE THREAD

**Issue by duramato** [BugraDayi/FakeAp#1]
When trying to connect to the AP dnsmasq's console keeps saying "DHCP paclet received on wlan0 which has no adress" but doesn't actually assign one.

**Comment by BugraDayi** [comment]
Disable ifplugd
Change in /etc/default/ifplugd, to this -
INTERFACES="eth0"
HOTPLUG_INTERFACES="eth0"
ARGS="-q -f -u0 -d10 -w -I"
SUSPEND_ACTION="stop"

Or you can try to remove ifplugd, probably it works

**Comment by duramato** [comment]
I don't even have ifplugd installed

**Comment by BugraDayi** [comment]
Which distribution do u use ?

**Comment by duramato** [comment]
Tried on Kali 2016.2

**Comment by BugraDayi** [comment]
I had tried on Kali 2016.2, I did not face any problem. Likely problem result from not getting IP  From network interface(wlan0 etc.)
Can you check whether or not your adapher have ip adress when you start FakeAp.
if there is no ip adress, you can set manually (ifconfig wlan0 10.0.0.1/24)

restart dhcpd and check your logs again to see if its still throwing the interface ignored error.

be sure to have lastest version of dnsmasq, because this problem was fixed
you can check this [link](https://dev.openwrt.org/changeset/32781)

**Comment by duramato** [comment]
I have dnsmasq v2.76
What fakap shows when Im prompted to select a device http://img.cla46.com/up/14749868815e05312.png
